# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['workflow_ui.py'],
    pathex=[],
    binaries=[
        # Explicitly include sqlite3 DLL on Windows if it exists
    ],
    datas=[('src', 'src')],
    hiddenimports=[
        # Core Python modules that sometimes get missed on Windows
        'sqlite3',
        '_sqlite3',
        'json',
        'datetime',
        'pathlib',
        'threading',
        'queue',
        'multiprocessing',
        'statistics',
        'math',
        'os',
        'sys',
        'tempfile',
        'shutil',
        'glob',
        'zipfile',
        'io',
        're',
        'time',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'html',
        'html.parser',
        # External dependencies
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.models',
        'requests.sessions',
        'requests.utils',
        'beautifulsoup4',
        'bs4',
        'bs4.builder',
        'bs4.builder._html5lib',
        'bs4.builder._htmlparser',
        'bs4.dammit',
        'urllib3',
        'urllib3.util',
        'urllib3.util.retry',
        'urllib3.poolmanager',
        'certifi',
        'charset_normalizer',
        'idna',
        # Tkinter GUI modules
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.constants',
        # Our application modules
        'gw2_leaderboard',
        'gw2_leaderboard.utils',
        'gw2_leaderboard.utils.sync_logs',
        'gw2_leaderboard.parsers',
        'gw2_leaderboard.parsers.parse_logs_enhanced',
        'gw2_leaderboard.core',
        'gw2_leaderboard.core.glicko_rating_system',
        'gw2_leaderboard.core.guild_manager',
        'gw2_leaderboard.core.rating_history',
        'gw2_leaderboard.web',
        'gw2_leaderboard.web.generate_web_ui',
        'gw2_leaderboard.web.data_processing',
        'gw2_leaderboard.web.parallel_processing',
        'gw2_leaderboard.web.file_generator',
        'gw2_leaderboard.web.templates',
        'gw2_leaderboard.web.templates.html_templates',
        'gw2_leaderboard.web.templates.css_styles',
        'gw2_leaderboard.web.templates.javascript_ui'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='workflow_ui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
